add_service_files() の GetGrid.srv,GetCalibs.srv のコメントアウトを外した。
★
srv/*.srv
と
CMakeLists.txtのadd_service_files()のファイルリスト
が一致していないと、jsで
const rovi_srvs = ros.require('rovi').srv;
TypeError: Cannot read property 'srv' of undefined
のようになってlaunchできないみたいなので。